### PR TITLE
Issue-1860: Update commons-fileupload:commons-fileupload from 1.3.3 to 1.4

### PR DESCRIPTION
**Pull request by flaix**
# Pull Request Description

This pull request closes strongbox/strongbox#1860

# Acceptance Test

* [x] Building the code of the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent) with `mvn clean install` still works.
* [x] Building the code of the [`strongbox`](https://github.com/strongbox/strongbox) project with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

# Code Review And Pre-Merge Checklist

* [x] My code follows the [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html) of this project.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code in hard-to-understand areas.
* [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by carlspring** [comment]
Hi,

Thanks for the pull request, but it will not work on our CI server, unless your branch is called `issue-1860`. Could you please rename the branch and re-create the pull request? Thanks! :)

**Comment by flaix** [comment]
Not a problem.
Thus might be worth a mention on the documentation page about Upgrading dependencies and plugins, don't you think?

**Comment by steve-todorov** [comment]
Yeah, it looks like we did not explicitly mention it in the docs. Thanks for the heads-up @flaix ! :)

**Comment by flaix** [comment]
Is this true for all pull requests on all repos? Then maybe it could be mentioned in a more general place, somewhere under contributing rules, I guess.

**Pull request closed without merging**
