### PR TITLE
Issue-1120 Updating the version of OrientDB

### PR DESCRIPTION
**Pull request by prbobba**
Tested the prerequisites (Acceptance Test) mentioned in https://github.com/strongbox/strongbox/issues/1120

### CODE REVIEW

**Comment by carlspring** [comment]
Thanks for your help and congratulations on your first pull request!

@strongbox/core-developers : Would you mind trying it out and confirming whether it works as expected?

**Comment by carlspring** [comment]
Have you tried building `strongbox-parent` -> `strongbox-db` -> `strongbox` ...?

**Comment by prbobba** [comment]
> Have you tried building `strongbox-parent` -> `strongbox-db` -> `strongbox` ...?

yes. I did that. No failures or issues observed. I will try to upload the console logs by EOD today (IST)

**Comment by carlspring** [comment]
To be considered for #1130, if it works without side-effects.

**Comment by carlspring** [comment]
@prbobba ,

Would you mind re-checking the following acceptance tests:

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

**Comment by carlspring** [comment]
With your changes against the `strongbox:master` i'm getting the following compilation error after building the `strongbox-parent` and `strongbox-db` projects:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /java/opensource/carlspring/strongbox-clean/strongbox-client/src/test/java/org/carlspring/strongbox/service/impl/ProxyRepositoryConnectionPoolConfigurationServiceImplIntegrationTest.java:[15,40] package org.springframework.test.context does not exist
[ERROR] /java/opensource/carlspring/strongbox-clean/strongbox-client/src/test/java/org/carlspring/strongbox/service/impl/ProxyRepositoryConnectionPoolConfigurationServiceImplIntegrationTest.java:[16,40] package org.springframework.test.context does not exist
[ERROR] /java/opensource/carlspring/strongbox-clean/strongbox-client/src/test/java/org/carlspring/strongbox/service/impl/ProxyRepositoryConnectionPoolConfigurationServiceImplIntegrationTest.java:[24,2] cannot find symbol
  symbol: class ActiveProfiles
[ERROR] /java/opensource/carlspring/strongbox-clean/strongbox-client/src/test/java/org/carlspring/strongbox/service/impl/ProxyRepositoryConnectionPoolConfigurationServiceImplIntegrationTest.java:[25,2] cannot find symbol
  symbol: class ContextConfiguration
[ERROR] /java/opensource/carlspring/strongbox-clean/strongbox-client/src/test/java/org/carlspring/strongbox/client/ArtifactResolverIntegrationTest.java:[16,40] package org.springframework.test.context does not exist
[ERROR] /java/opensource/carlspring/strongbox-clean/strongbox-client/src/test/java/org/carlspring/strongbox/client/ArtifactResolverIntegrationTest.java:[17,40] package org.springframework.test.context does not exist
[ERROR] /java/opensource/carlspring/strongbox-clean/strongbox-client/src/test/java/org/carlspring/strongbox/client/ArtifactResolverIntegrationTest.java:[24,2] cannot find symbol
  symbol: class ActiveProfiles
[ERROR] /java/opensource/carlspring/strongbox-clean/strongbox-client/src/test/java/org/carlspring/strongbox/client/ArtifactResolverIntegrationTest.java:[25,2] cannot find symbol
  symbol: class ContextConfiguration
[INFO] 8 errors 
```

**Comment by carlspring** [comment]
Closing.

**Pull request closed without merging**
