### PR TITLE
added JDK8/11 enforcement

### PR DESCRIPTION
**Pull request by ghost**
# Pull Request Description

This pull request closes strongbox/strongbox#

# Acceptance Test

* [X] Building the code of the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent) with `mvn clean install` still works.
* [X] Building the code of the [`strongbox`](https://github.com/strongbox/strongbox) project with `mvn clean install -Dintegration.tests` still works.
* [X] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [X] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [X] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [X] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [X] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [X] No

# Code Review And Pre-Merge Checklist

* [X] My code follows the [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html) of this project.
* [X] I have performed a self-review of my own code.
* [X] I have commented my code in hard-to-understand areas.
* [X] My changes generate no new warnings.

### CODE REVIEW

**Review by carlspring — APPROVED** [review]
LGTM! Thanks! :)

**Comment by steve-todorov** [comment]
Uhm... I'm sorry, but why is there a PR for this pointing to `issues/1649` ? This is already enforcement is already in the `master` branch? Merging this would result in conflicts.

**Comment by carlspring** [comment]
At the time, the `issues/1649` had probably not been rebased.

If this is now part of `issues/1649`, we can close it.

**Comment by sbespalov** [comment]
@carlspring @steve-todorov I think we need to rebase instead of merging this

**Comment by carlspring** [comment]
Okay.  In this case, I'll close it.

**Pull request closed without merging**
