### PR TITLE
Issue 1861: Upgrade commons-io:commons-io from 2.6 to 2.8.0

### PR DESCRIPTION
**Pull request by flaix**
# Pull Request Description

This pull request closes strongbox/strongbox#1861

# Acceptance Test

* [x] Building the code of the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent) with `mvn clean install` still works.
* [x] Building the code of the [`strongbox`](https://github.com/strongbox/strongbox) project with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

# Code Review And Pre-Merge Checklist

* [x] My code follows the [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html) of this project.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code in hard-to-understand areas.
* [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by flaix** [comment]
Reverted pom version back to 1.0-SNAPSHOT after all tests passed in strongbox/strongbox#1926

**Comment by carlspring** [comment]
Thanks very much! :)

**Comment by carlspring** [comment]
Could you please also test it with the `issues/1649` branch as well?

**Comment by flaix** [comment]
I have tested the `issues/1649` branch with commits 70bc437, 0c24f84 and 19eb110 cherry picked, i.e. `fileupload`version 1.4, `commons-collections4` version 4.4 and `commons-io` version 2.8.0.

`mvn clean install -Dintegration.test` runs successfully and Strongbox starts and works with `mvn spring-boot:run` as well as starting from the distribution. I have not run the SWIT.

**Pull request merged**
