### PR TITLE
issues/1775: Upgrade to Cassandra to 4.0-beta2

### PR DESCRIPTION
**Pull request by sbespalov**
Closes strongbox/strongbox#1775

### CODE REVIEW

**Review by carlspring — APPROVED** [review]
LGTM! Thanks!

**Comment by carlspring** [comment]
There appear to be some merge conflicts. Could you please resolve them?

**Review by carlspring — APPROVED** [review]
LGTM! Thanks for sorting out the merge conflicts and the noise! :)

**Comment by carlspring** [comment]
You're missing the `unboundid` dependency in the parent. The version for this is currently defined in the pull request for `strongbox` and it should moved here.

**Comment by sbespalov** [comment]
@carlspring the `unboundid` already there. I've dropped the version definition for it in `strongbox` project PR.

**Comment by carlspring** [comment]
Sorry, but I'm not seeing it in the diff here. Perhaps I'm missing something...? I know I just saw it in the pull for the `strongbox` project. Am I mistaken...?

**Review by carlspring — APPROVED** [review]
LGTM! Thanks! :)

**Pull request merged**
