### PR TITLE
Issue-1860: Update commons-fileupload:commons-fileupload from 1.3.3 to 1.4

### PR DESCRIPTION
**Pull request by flaix**
# Pull Request Description

This pull request closes strongbox/strongbox#1860

# Acceptance Test

* [x] Building the code of the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent) with `mvn clean install` still works.
* [x] Building the code of the [`strongbox`](https://github.com/strongbox/strongbox) project with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

# Code Review And Pre-Merge Checklist

* [x] My code follows the [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html) of this project.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code in hard-to-understand areas.
* [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by flaix** [comment]
Signed, sent and reverted.

**Comment by carlspring** [comment]
Thank you! Congratulations on your first pull request! :)

**Comment by carlspring** [comment]
As a follow-up task, could you please check, if this upgrade also works for the strongbox `issues/1649` branch (you can have a look at #62)? Thanks! :)

**Comment by flaix** [comment]
I take it that I have to build said branch for strongbox-db myself, as the PR-19 version is not deployed, is it?

**Comment by carlspring** [comment]
Sounds about right.

**Comment by flaix** [comment]
Do you want anything else done with that? I don't think you want the change on branch `issues/1649`, do you? That would result in conflicts when rebasing that branch onto master.

Man the integration tests run really long on this branch.

**Comment by carlspring** [comment]
Thanks for checking this! No need for further pull requests, or rebasing.

**Pull request merged**
