### PR TITLE
Excluding "org.testng:testng"

### PR DESCRIPTION
**Pull request by patro1322**
Fixes strongbox/strongbox#1547.

### CODE REVIEW

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by patro1322** [comment]
Updated the Contributing.MD page.

**Comment by carlspring** [comment]
I think you misunderstood me. There's a PDF file that you need to sign and e-mail me.

**Comment by patro1322** [comment]
> 
> 
> I think you misunderstood me. There's a PDF file that you need to sign and e-mail me.

Hi Martin,

I have sent you the signed copy of ICLA over email.

Thanks & Regards
Bishnu

**Pull request merged**
